UNAME := $(shell uname)

ifeq ($(UNAME), Linux)
    AS  =   as --32
    LD  =   ld 
    LDFLAGS = -m elf_i386 -x
    CC = gcc 
    CFLAGS = -g -m32 -fno-builtin -fno-stack-protector -fomit-frame-pointer -fstrengh-reduce

    CPP = cpp -nostdinc
    AR = ar 
    STRIP = strip
    OBJCOPY = objcopy 
    gcc_version=$(shell ls -l `which gcc` | tr '-' '\n' | tail -l)
endif